spring:
  #
  config:
    activate:
      on-profile: "mysql"
  #
  datasource:
    url: jdbc:mysql://mysql:3306/metaverse
    username: docker
    password: docker
---
spring:
  #
  config:
    activate:
      on-profile: "jpa"
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    # JPA Hibernate (ORM)을 통해 변환 처리된 SQL 쿼리문을 로그로 남긴다.
    show-sql: true